package com.example.geopulse.ui.news

val famousCountries = listOf(
    Country("India", "🇮🇳"),
    Country("United States", "🇺🇸"),
    Country("Russia", "🇷🇺"),
    Country("China", "🇨🇳"),
    Country("Israel", "🇮🇱"),
    Country("Iran", "🇮🇷"),
    Country("Pakistan", "🇵🇰"),
    Country("Ukraine", "🇺🇦"),
    Country("Germany", "🇩🇪"),
    Country("France", "🇫🇷"),
    Country("United Kingdom", "🇬🇧"),
    Country("Japan", "🇯🇵"),
    Country("South Korea", "🇰🇷"),
    Country("North Korea", "🇰🇵"),
    Country("Turkey", "🇹🇷"),
    Country("Saudi Arabia", "🇸🇦"),
    Country("UAE", "🇦🇪"),
    Country("Afghanistan", "🇦🇫"),
    Country("Iraq", "🇮🇶"),
    Country("Syria", "🇸🇾"),
    Country("Yemen", "🇾🇪"),
    Country("Egypt", "🇪🇬"),
    Country("Nigeria", "🇳🇬"),
    Country("Brazil", "🇧🇷"),
    Country("Argentina", "🇦🇷"),
    Country("Canada", "🇨🇦"),
    Country("Australia", "🇦🇺"),
    Country("Spain", "🇪🇸"),
    Country("Italy", "🇮🇹"),
    Country("Mexico", "🇲🇽")
)